# Generated by Django 4.1.1 on 2022-09-23 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mana_cost', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('flavor', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=100)),
                ('collector_number', models.IntegerField()),
                ('power', models.CharField(max_length=3)),
                ('toughness', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shorthand', models.CharField(max_length=20)),
                ('icon', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.card')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.type')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.set'),
        ),
    ]
