# Generated by Django 4.1.1 on 2022-09-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='search_uri',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
