# Generated by Django 4.1.1 on 2022-09-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_set_search_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_type',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
