# Generated by Django 4.1.1 on 2022-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_set_set_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(default='no', max_length=36),
            preserve_default=False,
        ),
    ]
