# Generated by Django 4.1.1 on 2022-09-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_card_scryfall_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flavor',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
