# Generated by Django 4.1.1 on 2022-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_card_flavor_alter_card_power_alter_card_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='collector_number',
            field=models.CharField(max_length=6),
        ),
    ]
