# Generated by Django 4.1.1 on 2022-09-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_card_collector_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='converted_cost',
            field=models.IntegerField(null=True),
        ),
    ]
