# Generated by Django 4.1.1 on 2022-09-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_card_image_flipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTG_Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='CardType',
        ),
        migrations.AddField(
            model_name='card',
            name='oracle_id',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='collection.MTG_Rarity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set',
            name='set_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.settype'),
        ),
    ]
