# Generated by Django 4.0.8 on 2022-10-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_mtgcollected_card_mtgcollected_foil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(max_length=50),
        ),
    ]
