# Generated by Django 4.0.8 on 2022-10-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_alter_card_flavor_alter_card_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='collector_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
