# Generated by Django 4.0.8 on 2022-10-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_rename_card_mtg_card_rename_cardtype_mtg_cardtype_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MTG_Rarity',
            new_name='MTG_Rarity_e',
        ),
    ]
