# Generated by Django 4.0.8 on 2022-10-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_rename_mtg_rarity_mtg_rarity_e'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MTG_Rarity_e',
            new_name='MTG_Rarity',
        ),
    ]
