# Generated by Django 4.0.8 on 2022-11-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_rename_mtg_rarity_e_mtg_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtg_card',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mtg_card',
            name='mana_cost',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mtg_set',
            name='icon',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
