# Generated by Django 4.0.8 on 2022-11-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_mtg_custom_set_mtg_custom_set_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtg_custom_set',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
