# Generated by Django 4.0.8 on 2022-11-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_alter_mtg_custom_set_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg_custom_set_cards',
            name='foil',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtg_custom_set_cards',
            name='normal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
