# Generated by Django 4.1.1 on 2022-09-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcgct_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
